/**
 * mockData.ts
 * Mock anime data for development
 * Replace with real Kitsu API data once API issues are resolved
 */

import type { KitsuResponse } from '../types/anime';

export const mockAnimeData: KitsuResponse = {
  data: [
    {
      id: '1',
      type: 'anime',
      attributes: {
        title: 'Naruto',
        description: 'Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure Village at the periphery of the land.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/1/large.jpg' },
        averageRating: 78,
        episodeCount: 220,
        status: 'finished',
        startDate: '2002-10-03',
        endDate: '2007-02-08',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '5',
      type: 'anime',
      attributes: {
        title: 'Cowboy Bebop',
        description: 'In 2071, space travel is routine, and Interstellar Police is busy chasing criminals around the solar system.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/5/large.jpg' },
        averageRating: 88,
        episodeCount: 26,
        status: 'finished',
        startDate: '1998-04-03',
        endDate: '1999-04-24',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '6',
      type: 'anime',
      attributes: {
        title: 'Trigun',
        description: 'Vash the Stampede is the man with a price on his head. The bad news is they call him the "Human Typhoon".',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/6/large.jpg' },
        averageRating: 76,
        episodeCount: 26,
        status: 'finished',
        startDate: '1998-04-01',
        endDate: '1999-09-30',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '7',
      type: 'anime',
      attributes: {
        title: 'One Piece',
        description: 'As a child, Monkey D. Luffy was inspired to become a pirate by listening to the tales of the buccaneer "Red-Haired" Shanks.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/7/large.jpg' },
        averageRating: 84,
        episodeCount: 1100,
        status: 'current',
        startDate: '1999-10-20',
        endDate: null,
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '8',
      type: 'anime',
      attributes: {
        title: 'Neon Genesis Evangelion',
        description: 'In the year 2015, the world stands on the brink of destruction. Humanity has created giant robots.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/8/large.jpg' },
        averageRating: 74,
        episodeCount: 26,
        status: 'finished',
        startDate: '1995-10-04',
        endDate: '1996-03-27',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '9',
      type: 'anime',
      attributes: {
        title: 'Attack on Titan',
        description: 'Many years ago, the last remnants of humanity were forced to retreat behind the towering walls of a walled city.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/9/large.jpg' },
        averageRating: 85,
        episodeCount: 139,
        status: 'finished',
        startDate: '2013-04-07',
        endDate: '2023-04-04',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '11',
      type: 'anime',
      attributes: {
        title: 'Death Note',
        description: 'Light Yagami is a shinigami who finds a notebook that allows him to kill anyone by writing their name.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/11/large.jpg' },
        averageRating: 88,
        episodeCount: 37,
        status: 'finished',
        startDate: '2006-10-04',
        endDate: '2007-06-27',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '12',
      type: 'anime',
      attributes: {
        title: 'Fullmetal Alchemist',
        description: 'Two brothers, Edward and Alphonse Elric, attempt a forbidden alchemical transmutation.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/12/large.jpg' },
        averageRating: 86,
        episodeCount: 51,
        status: 'finished',
        startDate: '2005-07-09',
        endDate: '2010-07-04',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    // Additional anime to support pagination (9-36)
    {
      id: '13',
      type: 'anime',
      attributes: {
        title: 'Bleach',
        description: 'Ichigo Kurosaki is a high school student who can see ghosts.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/13/large.jpg' },
        averageRating: 80,
        episodeCount: 366,
        status: 'finished',
        startDate: '2004-10-05',
        endDate: '2012-12-25',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '14',
      type: 'anime',
      attributes: {
        title: 'Jujutsu Kaisen',
        description: 'A high schooler unexpectedly swallows a cursed talisman and becomes host to a powerful demon.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/14/large.jpg' },
        averageRating: 87,
        episodeCount: 50,
        status: 'current',
        startDate: '2020-10-03',
        endDate: null,
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '15',
      type: 'anime',
      attributes: {
        title: 'My Hero Academia',
        description: 'In a world where most of the population has superpowers, Izuku dreams of becoming a hero.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/15/large.jpg' },
        averageRating: 83,
        episodeCount: 139,
        status: 'current',
        startDate: '2016-04-03',
        endDate: null,
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '16',
      type: 'anime',
      attributes: {
        title: 'Demon Slayer',
        description: 'After his family is slaughtered by demons, Tanjiro embarks on a journey to save his sister.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/16/large.jpg' },
        averageRating: 86,
        episodeCount: 55,
        status: 'current',
        startDate: '2019-04-06',
        endDate: null,
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '17',
      type: 'anime',
      attributes: {
        title: 'Tokyo Ghoul',
        description: 'A college student is transformed into a ghoul after an encounter with a ghoul.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/17/large.jpg' },
        averageRating: 79,
        episodeCount: 48,
        status: 'finished',
        startDate: '2014-07-04',
        endDate: '2018-12-25',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '18',
      type: 'anime',
      attributes: {
        title: 'Steins;Gate',
        description: 'A group of students discover they can send messages to the past and alter the timeline.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/18/large.jpg' },
        averageRating: 90,
        episodeCount: 24,
        status: 'finished',
        startDate: '2011-04-09',
        endDate: '2011-09-14',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '19',
      type: 'anime',
      attributes: {
        title: 'Code Geass',
        description: 'Lelouch gains the power to command anyone he makes eye contact with.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/19/large.jpg' },
        averageRating: 81,
        episodeCount: 50,
        status: 'finished',
        startDate: '2006-10-06',
        endDate: '2008-07-29',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '20',
      type: 'anime',
      attributes: {
        title: 'Mob Psycho 100',
        description: 'A middle school boy with psychic powers tries to live a normal life.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/20/large.jpg' },
        averageRating: 85,
        episodeCount: 25,
        status: 'finished',
        startDate: '2016-07-12',
        endDate: '2016-10-04',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '21',
      type: 'anime',
      attributes: {
        title: 'Sword Art Online',
        description: 'Players are trapped in a virtual reality MMORPG and must clear all 100 floors to escape.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/21/large.jpg' },
        averageRating: 74,
        episodeCount: 96,
        status: 'finished',
        startDate: '2012-07-08',
        endDate: '2021-12-25',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '22',
      type: 'anime',
      attributes: {
        title: 'Chainsaw Man',
        description: 'A poor boy with a chainsaw demon merged into his body fights devils for a living.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/22/large.jpg' },
        averageRating: 84,
        episodeCount: 12,
        status: 'current',
        startDate: '2022-10-11',
        endDate: null,
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '23',
      type: 'anime',
      attributes: {
        title: 'Akira',
        description: 'In a dystopian future, a biker gang member discovers psychic powers.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/23/large.jpg' },
        averageRating: 81,
        episodeCount: 1,
        status: 'finished',
        startDate: '1988-07-16',
        endDate: '1988-07-16',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '24',
      type: 'anime',
      attributes: {
        title: 'Puella Magi Madoka Magica',
        description: 'A young girl is offered magical powers by a mysterious creature.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/24/large.jpg' },
        averageRating: 84,
        episodeCount: 12,
        status: 'finished',
        startDate: '2011-01-08',
        endDate: '2011-04-23',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '25',
      type: 'anime',
      attributes: {
        title: 'Ergo Proxy',
        description: 'In a post-apocalyptic world, a girl seeks answers about her existence.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/25/large.jpg' },
        averageRating: 77,
        episodeCount: 23,
        status: 'finished',
        startDate: '2006-02-13',
        endDate: '2006-08-14',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '26',
      type: 'anime',
      attributes: {
        title: 'Ghost in the Shell',
        description: 'A cyborg special ops team fights terrorists and criminals in a futuristic Japan.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/26/large.jpg' },
        averageRating: 80,
        episodeCount: 26,
        status: 'finished',
        startDate: '2002-10-06',
        endDate: '2005-03-08',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '27',
      type: 'anime',
      attributes: {
        title: 'Vinland Saga',
        description: 'A former warrior seeks revenge on the man who killed his father.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/27/large.jpg' },
        averageRating: 88,
        episodeCount: 24,
        status: 'finished',
        startDate: '2019-07-07',
        endDate: '2019-12-29',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '28',
      type: 'anime',
      attributes: {
        title: 'Spy x Family',
        description: 'A spy, assassin, and telepath form a fake family for a mission.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/28/large.jpg' },
        averageRating: 86,
        episodeCount: 25,
        status: 'current',
        startDate: '2022-04-09',
        endDate: null,
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '29',
      type: 'anime',
      attributes: {
        title: 'Samurai Champloo',
        description: 'A girl travels with two samurai with opposing fighting styles in Edo period Japan.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/29/large.jpg' },
        averageRating: 82,
        episodeCount: 26,
        status: 'finished',
        startDate: '2004-05-16',
        endDate: '2005-03-19',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '30',
      type: 'anime',
      attributes: {
        title: 'Paprika',
        description: 'A scientist\'s experimental drug allows people to share their dreams.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/30/large.jpg' },
        averageRating: 83,
        episodeCount: 1,
        status: 'finished',
        startDate: '2006-11-25',
        endDate: '2006-11-25',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '31',
      type: 'anime',
      attributes: {
        title: 'Natsume\'s Book of Friends',
        description: 'A boy with the ability to see spirits inherits a book of supernatural beings.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/31/large.jpg' },
        averageRating: 82,
        episodeCount: 77,
        status: 'finished',
        startDate: '2008-07-07',
        endDate: '2017-06-26',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '32',
      type: 'anime',
      attributes: {
        title: 'Gintama',
        description: 'A samurai, his apprentice, and a girl try to make a living in an alien-invaded Japan.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/32/large.jpg' },
        averageRating: 84,
        episodeCount: 201,
        status: 'finished',
        startDate: '2006-04-04',
        endDate: '2010-03-29',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
    {
      id: '33',
      type: 'anime',
      attributes: {
        title: 'Hellbound',
        description: 'Supernatural beings condemn people to hell, causing mass chaos and religious fervor.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/33/large.jpg' },
        averageRating: 75,
        episodeCount: 6,
        status: 'finished',
        startDate: '2021-11-19',
        endDate: '2021-11-19',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '34',
      type: 'anime',
      attributes: {
        title: 'Devilman Crybaby',
        description: 'A kind-hearted boy merges with a demon and joins the demon realm as an avenger.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/34/large.jpg' },
        averageRating: 79,
        episodeCount: 10,
        status: 'finished',
        startDate: '2018-01-05',
        endDate: '2018-02-16',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '35',
      type: 'anime',
      attributes: {
        title: 'Fate/Zero',
        description: 'Seven mages summon servants to fight for a magical wish-granting Holy Grail.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/35/large.jpg' },
        averageRating: 85,
        episodeCount: 25,
        status: 'finished',
        startDate: '2011-10-01',
        endDate: '2012-06-23',
        ageRating: 'R',
        ageRatingGuide: null,
      },
    },
    {
      id: '36',
      type: 'anime',
      attributes: {
        title: 'HunterxHunter',
        description: 'A boy dreams of becoming a hunter and finding his father in a dangerous world.',
        posterImage: { original: 'https://media.kitsu.io/anime/poster_images/36/large.jpg' },
        averageRating: 87,
        episodeCount: 148,
        status: 'finished',
        startDate: '2011-10-02',
        endDate: '2014-09-23',
        ageRating: 'PG',
        ageRatingGuide: null,
      },
    },
  ],
  meta: {
    count: 36,
  },
};